spring.application.name=collegeManagementSystem
spring.datasource.url=jdbc:mysql://localhost:3306/collegeManagementSystem
spring.datasource.username=root
spring.datasource.password=root@618

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.open-in-view=false